import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Layout from "@/components/Layout";
import { useEffect, useRef, useState } from "react";
import Typewriter from "typewriter-effect";
import { Fade } from "react-reveal";
import { FaCaretDown } from "react-icons/fa";
import Link from "next/link";
import CosretFeatures from "@/components/CosretFeatures";
import MeetTheTeam from "@/components/MeetTheTeam";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  const scrollRef = useRef(null);

  const scrollDown = () => {
    window.scrollTo({
      top: scrollRef.current?.offsetTop - 120,
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>COSRET | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* HERO SECTION */}
        <div className="flex text-lwft flex-col align-middle pt-32 px-7 min-h-screen">
          <h1 className="text-4xl font-bold">About COSRET</h1>
          <p className="mt-5">
            Design and implementation of a collaborative software requirement
            engineering tool.
          </p>

          <div className="flex flex-col justify-center align-middle"></div>
        </div>

        <div className="px-7 mb-32">
          <MeetTheTeam />
        </div>

        {/* About COSRET */}
      </Layout>
    </>
  );
}
