import Head from "next/head";
import FAQSection from "@/components/FAQSection";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import HeadingAndSubtext from "@/components/HeadingAndSubtext";
import ContactForm from "@/forms/ContactForm";

export default function Support() {
  return (
    <>
      <Head>
        <title>Cosret | Support</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* HERO SECTION */}

        <section className="w-full text-center my-20 mb-72">
          <HeadingAndSubtext
            heading="Reach out to us"
            subtext="We typically reply in less than 5 minutes"
          />
          {/* CONTACT US FORM */}
          <div className="mt-16">
            <ContactForm />
          </div>
        </section>

        {/* GOT QUESTIONS? */}
        <div className="my-32">
          <FAQSection />
        </div>

        {/* FOOTER */}
        <Footer />
      </Layout>
    </>
  );
}
