import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Layout from "@/components/Layout";
import { createContext, useContext, useEffect, useRef, useState } from "react";
import Typewriter from "typewriter-effect";
import { Fade } from "react-reveal";
import { FaCaretDown } from "react-icons/fa";
import Link from "next/link";
import CosretFeatures from "@/components/CosretFeatures";
import FAQSection from "@/components/FAQSection";
import AvailableGlobally from "@/components/MeetTheTeam";
import MeetTheTeam from "@/components/MeetTheTeam";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const scrollRef = useRef(null);

  const scrollDown = () => {
    window.scrollTo({
      top: scrollRef.current?.offsetTop - 120,
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>COSRET | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* HERO SECTION */}
        <div className="flex text-center flex-col align-middle pt-48 px-7 min-h-screen">
          <h1 className="text-4xl font-bold">
            <Typewriter
              options={{
                strings: [
                  "Submit User Requirements.",
                  "Evaluate System Requirements.",
                  "Download Final Specification.",
                ],
                autoStart: true,
                loop: true,
                delay: 75,
                deleteSpeed: 50,
              }}
            />
          </h1>
          <p className="mt-5">
            Design and implementation of a collaborative software requirement
            engineering tool.
          </p>

          <div className="flex flex-col justify-center align-middle"></div>

          <Link
            href="/how-it-works"
            className="h-16 w-48 mx-auto mt-12 rounded-lg flex justify-center align-middle text-white my-5 py-3 px-7 bg-black"
          >
            <span className="my-auto">Get started</span>
          </Link>
          <Link
            href="/about"
            className="h-16 w-48 mx-auto rounded-lg flex justify-center align-middle text-black my-5 py-3 px-7 bg-transparent border-black border-2"
          >
            <span className="my-auto">Learn more</span>
          </Link>

          <div className="flex justify-center w-full mt-20">
            <Fade duration={800} delay={1000}>
              <FaCaretDown
                size={35}
                style={{
                  padding: "4px",
                  borderWidth: "2px",
                  borderColor: "black",
                  borderRadius: "50%",
                  cursor: "pointer",
                }}
                onClick={scrollDown}
              />
            </Fade>
          </div>
        </div>

        <div className="px-7" ref={scrollRef}>
          <CosretFeatures />
        </div>

        {/* Meet the team */}
        <MeetTheTeam />

        {/* FAQs */}
        <FAQSection />
      </Layout>
    </>
  );
}
